### ISSUE TITLE
highlight.js not working properly

### ISSUE THREAD

**Issue by Gheek** [nishanths/cocoa-hugo-theme#30]
Hello guys,
It seems there is something wrong with highlightjs. 
For example in the demo: http://themes.gohugo.io/theme/cocoa/blog/use-at-instead-of-head/
When putting firefox in debugging mode I cannot see why its not working. Any ideas?

**Comment by nishanths** [comment]
@Gheek thanks for reporting

it looks like it was because the content was using the old `{{ <highlight code> }}` syntax instead of the standard markdown code fences.

Hugo appears to support both now, so I've switched to using code fences. We will need to wait for themes.gohugo.io to rebuild the theme, so I will leave this issue open until then.
