### ISSUE TITLE
Markdown incomplete for fixed pages in content root

### ISSUE THREAD

**Issue by bnjmn** [nishanths/cocoa-hugo-theme#36]
I haven't had a chance to isolate how or why this issue is happening but here are the steps to reproduce ...

Based on the `README`, I was under the impression both locations for the fixed pages should produce the same results:

> Fixed pages such as an About page should preferably go under a content/fixed or be present at the root of the contents directory.

---

### Fixed pages in content root do not render all markdown 

1. Put the `about.md` page in `content/fixed/.`. Be sure to include subtitle with "### subtitle" or inline code with "\`code here\`"
2. View the content in browser. Markdown should be formatted correctly.
3. Move the file to `content/about.md`.
3. [**Issue**] The markdown will not be fully rendered. No subtitle or inline code formatting. These will look like normal text

# Screenshots

## `content/fixed/about.md`

<img width="699" alt="screen shot 2016-12-05 at 1 25 56 pm" src="https://cloud.githubusercontent.com/assets/727509/20897105/ab6f914e-baee-11e6-8799-cc8200b0d0e0.png">

---

## `content/about.md`
<img width="708" alt="screen shot 2016-12-05 at 1 27 35 pm" src="https://cloud.githubusercontent.com/assets/727509/20897109/ae51b2ca-baee-11e6-9266-9f62bb3379d4.png">

**Comment by nishanths** [comment]
@bnjmn thanks for catching this.

Haven't dug into it yet, but initial thoughts: it's likely happening because [`fixed/single.html`](https://github.com/nishanths/cocoa-hugo-theme/blob/490bf5858d4857c4ea98c0bb752906fd647fc5f5/layouts/fixed/single.html) has the `markdown` class, but [`_default/single.html`](https://github.com/nishanths/cocoa-hugo-theme/blob/490bf5858d4857c4ea98c0bb752906fd647fc5f5/layouts/_default/single.html) does not.

Will update `README` / `_default/single.html` after checking.

**Comment by bnjmn** [comment]
Nice. I'm new to Hugo (and go) and haven't had a chance to really dive into the source. I'm surprised the Markdown files (`*.md`) don't handle this automatically.

**Comment by nishanths** [comment]
@bnjmn i believe the markdown files are handling it automatically (for instance you can see the gray code block and bold text), but the default styles don't look as nicely formatted as the custom CSS.

**Comment by nishanths** [comment]
@bnjmn HTML files in `content` root should now look exactly like those in `content/fixed`. Thanks!
