### ISSUE TITLE
The "base href" parameter is doing more harm than good

### ISSUE THREAD

**Issue by vkobel** [nishanths/cocoa-hugo-theme#58]
Hi,
I stumbled upon this great theme I use for my personal [blog](https://kobl.one/), thanks to @nishanths for that!

However one tiny little detail bothered me: the use of `<base href="{{ .Site.BaseURL }}">` tag in the [partial head.html](https://github.com/nishanths/cocoa-hugo-theme/blob/master/layouts/partials/head.html#L3).
Is it really necessary in this case? I understand how this could be useful, but here it's doing more harm than good IMHO.

My (very specific) issue was when I tried to put my public/ blog on [IPFS](https://ipfs.io/). Over there all the URLs are prefixed by `/ipfs/[content hash]/` like this: https://ipfs.io/ipns/Qmdr8MhNeWE1sxABevBvxWNWC25iXEicfJRvYNpuCpca8E/ and the base tag is making it not working because the blog isn't at the root of the URL.

I didn't bother to make a pull request as the fix would simply be to remote the `<base>` tag. What do you think?

Have a good one!
Vincent

**Comment by nishanths** [comment]
does setting `baseurl = https://ipfs.io/ipns/<contenthash>/` in `config.toml` fix the issue? https://github.com/nishanths/cocoa-hugo-theme/blob/master/exampleSite/config.toml#L1

if not, let me know

**Comment by vkobel** [comment]
I'm sure it does. I was just questioning the purpose of this base tag actually. By removing it, everything works as expected. Or did I miss something?

**Comment by nishanths** [comment]
Hi @vkobel, sorry about the delay! I did not think it through completely when initially adding the `<base href>` tag, and it does seem to be causing more pain than good. For example, here's a related issue: https://github.com/nishanths/cocoa-hugo-theme/issues/56.

I'm happy to merge a pull request that removes the tag :)

As for why removing it works, it might be because the relative URLs for your web page assets are now being resolved correctly.

**Comment by vkobel** [comment]
Hey, thanks for your answer.
Pull request #59 has been submitted :+1:

**Comment by nishanths** [comment]
closed via #59
