### ISSUE TITLE
Custom content requires 'index' in its path

### ISSUE THREAD

**Issue by wooken** [nishanths/cocoa-hugo-theme#77]
## Desired effect

Achieve the following link `http://localhost:1313/hi`.

## Issue

The following directories:

> /content/hi.md
> /content/fixed/hi.md

Don't map to any of the layouts:

> /layouts/hi.html
> /layouts/hi/single.html

## Current Workaround

Use the link `http://localhost:1313/hi9000/index` with the following:

> /content/hi9000/index.md
> /layouts/hi9000/single.html

In order to achieve the desired effect, I am currently using this alias in `hi9000.md`:

```
+++
title = "hello world"
aliases = [
    "/hi",
]
+++
```

## Question

How can I achieve the desired effect that doesn't have `index` in the URL?

**Comment by lpancescu** [comment]
This is due to how Hugo works, nothing specific to this theme. The first-level directories under *content* determine the section and the default type (you can override the latter in the front matter of your post).  In your case:

* `content/hi.md`: default section, default type
* `content/fixed/hi.md`: section *fixed*, type *fixed*

The theme currently expects your non-blog pages to be under `fixed`, so you could use `content/fixed/hi.md` and add `type = "hi"` to the frontmatter (or `layout = "hi"` if you want to use a custom layout).

http://gohugo.io/templates/content/

**Comment by wooken** [comment]
Thank you for the detailed explanation along with the documentation link, @lpancescu. Your solution works.
