### ISSUE TITLE
Add an instagram link

### ISSUE THREAD

**Issue by danielsiwiec** [nishanths/cocoa-hugo-theme#89]
Hi, it would be great to add instagram to the list of available links (next to facebook, email, github, linked, etc). I'd be happy to submit a PR for this

**Comment by nishanths** [comment]
yes, please make a PR, thanks!

**Comment by danielsiwiec** [comment]
Hmm. @nishanths where did you get the svgs from? I'm having a hard time finding a similar one, at similar size.

**Comment by lpancescu** [comment]
@danielsiwiec You could use the public domain SVG from https://commons.wikimedia.org/wiki/File:Instagram_Shiny_Icon.svg (resize to 16x16 in Inkscape and optimize with [svgo][]). It would be the only colored icon in a row of black-white icons, but I guess you can't change that due to trademark issues.

[svgo]: https://github.com/svg/svgo

**Comment by danielsiwiec** [comment]
@nishanths @lpancescu Created PR #97
